### ISSUE TITLE
How to get the paper's Dice?

### ISSUE THREAD

**Issue by meetbbh223** [YazhouZhu19/RPT#10]
Dear author,
         Thanks for you read this issue.  When I use your code to train and test on database SABS,  I found that I just can't reach the Dice Scores  shown in your paper. I hope you can help me check my Config, which is laid below:
![image](https://github.com/YazhouZhu19/RPT/assets/136066918/bae471d0-f7dd-4268-8a79-2728704dd979)
![image](https://github.com/YazhouZhu19/RPT/assets/136066918/cb7d7bc2-1a38-45c1-a244-0c7f3824892c)

when I use the Experiment Setup as your paper said (30K iterations in total , decay of 0.8 every 1000 iterations, etc) to train this model, the test scores is far from the paper. It just hit 6-14% Dice scores. Besides, I noticed that the loss scores hardly decrease under your paper's Config.  All the experiments are trained under NVIDIA RTX3090, but the training time only took up 5 hours.

**Comment by YazhouZhu19** [comment]
Hi, Sorry for the delay in replying and thank you for attention.
I have updated the files: models/fewshot.py  train.py  test.py and uploaded the trained models for three datasets under setting 1 and setting 2.
You can run and check the results.
Thanks again for attention.

**Comment by meetbbh223** [comment]
thanks for your reply
