### ISSUE TITLE
how to see the predicted results

### ISSUE THREAD

**Issue by ibasaisaac** [YazhouZhu19/RPT#13]
Hello.  I am having a problem visualizing the predicted 3D images and comparing them with ground truth as you have shown in your paper. Could you provide instructions or resources on how to accomplish this?

**Comment by YazhouZhu19** [comment]
Hi, thanks for attention.
The visualizing codes will be uploaded later.

**Comment by ibasaisaac** [comment]
Thank you for the reply. Will be waiting for the code update...

**Comment by YazhouZhu19** [comment]
Code is included in folder visualization, you can try it.
