### ISSUE TITLE
BUG in class TrainDataset(Dataset)

### ISSUE THREAD

**Issue by LeeX-Bruce** [YazhouZhu19/RPT#16]
Hello author. I found a bug in the `datasets.py` file with settings that don't match the description in the paper.

The `__getitem__` method in `class TrainDataset`, which should get the index of the slices of this patient that contain the` exclude_label` in case `exclude_label` is passed in, has the following original code:
```
exclude_idx = np.full(gt.shape[0], True, dtype=bool)
for i in range(len(self.exclude_label)):
    exclude_idx = exclude_idx & (np.sum(gt == self.exclude_label[i], axis=(1, 2)) > 0)
    print(f'{i}_exclude_idx: {idx[exclude_idx]}')
exclude_idx = idx[exclude_idx]
```
Its does not achieve the above effect. If my `exclude_label` is **[1, 2, 3, 4]**, then the `exclude_idx` I get in patient 38 and the `sli_idx` I get later is shown below:
![image](https://github.com/YazhouZhu19/RPT/assets/56881416/37d300e6-00ce-49ac-97fb-0040ae913e5f)

Here is the code I corrected(Probably?):
```
exclude_idx = np.full(gt.shape[0], False, dtype=bool)
for i in range(len(self.exclude_label)):
    exclude_idx = exclude_idx | (np.sum(gt == self.exclude_label[i], axis=(1, 2)) > 0)
exclude_idx = idx[exclude_idx]
```
The result is as follows：
![image](https://github.com/YazhouZhu19/RPT/assets/56881416/ce3666d4-949b-454e-8e06-0184e3d965c0)

**Comment by YazhouZhu19** [comment]
Hi, LeeX-Bruce

We are grateful that you points out bugs in the `datasets.py` file. We directly employ the dataloader files from the repository [https://github.com/ZJLAB-AMMI/Q-Net/tree/main/dataloaders](url). 

We will update the dataloader code files according to your comments

**Comment by LeeX-Bruce** [comment]
Okay, thanks for the reply.
