### ISSUE TITLE
visualization of the other datasets 

### ISSUE THREAD

**Issue by ibasaisaac** [YazhouZhu19/RPT#18]
Hello. Thank you so much for providing the code for visualization. However, since the visualization code is for CMR, I am unable to run the code as I still haven't received the dataset from the MS-CMR Challenge. Moreover, I am unable to make changes to make the code work for CHAOST2 or SABS. 

So I hope you will provide the visualization code for the other datasets.

**Comment by YazhouZhu19** [comment]
Hi, visualization codes for the other datasets are uploaded.
