### ISSUE TITLE
About the code section in the paper compared to other models

### ISSUE THREAD

**Issue by WangBingJian233** [YazhouZhu19/RPT#2]
Dear author, thank you very much for your outstanding contribution. May I ask you about the comparison experiments with other models in your paper? For the two papers CRAPNet (WACV'23) and SR&CL (MICCAI'22), I did not find the source code published by the author. May I ask whether the author published the source code but I did not find it? Or did you reproduce it yourself from the original paper? (Is it convenient for you to publish the source code for these two models?)

**Comment by YazhouZhu19** [comment]
Hi, Sorry for the delay in replying.
I didn't find the implement code of CRAPNet and SR&CL.
