### ISSUE TITLE
Experimental precision issues.

### ISSUE THREAD

**Issue by 1islist** [YazhouZhu19/RPT#6]
I reproduced your code and found that the experimental accuracy is far from the paper, I would like to know how did you calculate the final accuracy? Even the experimental results I got in the 50% fold cross validation and using the best supported image are 3 points off from the article results.

**Comment by meetbbh223** [comment]
May I ask which datasets you take to train? MRI or CT?  When I use CT , the scores hit merely 6-14%.

**Comment by YazhouZhu19** [comment]
Hi, Sorry for the delay in replying and thank you for attention.
I have updated the files: models/fewshot.py train.py test.py and uploaded the trained models for three datasets under setting 1 and setting 2.
You can run and check the results.
Thanks again for attention.
