### ISSUE TITLE
Training and testing problems on SABS dataset

### ISSUE THREAD

**Issue by WangBingJian233** [YazhouZhu19/RPT#7]
Dear author, when I conducted the SABS dataset experiment with your code and the pre-treated SABS hypervoxels you provided, the test results are SPLEEN, RK, LK and GALLBLADDER, but not SPLEEN, RK, LK and Liver as mentioned in this paper. Besides, GALLBLADDER has a very low DICE score on organ segmentation. What's the matter? Is the dataset == 'SABS' part of def get_label_names(dataset) in dataset_specifics.py incorrect (as shown in the figure below)? Could you please modify it?
![image](https://github.com/YazhouZhu19/RPT/assets/59432372/7f6a9a0e-5fa0-4d03-a1a8-21421094d435)

**Comment by yunfeixie233** [comment]
Hi @WangBingJian233,

I came across your issue here as I'm facing a similar problem. Just wondering, were you able to find a solution?

**Comment by YazhouZhu19** [comment]
Hi, Sorry for the delay in replying and thank you for attention.
I have updated the files: models/fewshot.py train.py test.py and uploaded the trained models for three datasets under setting 1 and setting 2.

Sorry for not giving the running scripts for SABS datasets, we upload the scripts `train_SABS_setting1.sh` and `train_SABS_Setting2.sh` for training model on the SABS dataset. We just employ  SPLEEN, RK, LK and Liver  these four organs as the preliminary attempt for the few-shot medical image segmentation, and more work is doing. 
We are grateful that you are interested in our work! 
Any questions feel free to contact me, and thanks again!
