### ISSUE TITLE
About Settings 1 and 2

### ISSUE THREAD

**Issue by LeeX-Bruce** [YazhouZhu19/RPT#8]
Hello author, thank you very much for your excellent work.

I have a question about the code: What are the parameters in the code for setting 1 and setting 2? I see this code in the config.py `exclude_label = [1,2,3,4] # None, for not excluding test labels; Setting 1: None, Setting 2: True`, if I want to run setting 1, do I need to change it to `None`? What other parameters are there that I need to modify？

Or do I only need to modify the two parameters of `EXCLUDE_LABEL=None TEST=1234` in the train.sh to set 1 and 2？

**Comment by YazhouZhu19** [comment]
Hi, the scripts should be modified as:
For dataset CHAOST2:
Setting1: `exclude_label = None`  Setting2: `exclude_label = [1,2,3,4]`
For dataset SABS:
Setting1: `exclude_label = None`  Setting2: `exclude_label=[1,2,3,6]`

Any questions feel free to contact me.
